### ISSUE TITLE
How do I recompile the vue component?

### ISSUE THREAD

**Issue by lYesterdaYl** [Bottelet/DaybydayCRM#208]
I want to make an adjustment on the Graphline.vue. How can I recompile it? Any helps are appreciated.

**Comment by Bottelet** [comment]
Hi @lYesterdaYl 
Running yarn run dev or yarn watch should fix the problem.

**Comment by lYesterdaYl** [comment]
Hi, I got this error upon running the command.

```
C:\xampp\htdocs\mplus>npm rebuild node-sass

C:\xampp\htdocs\mplus>yarn run dev
yarn run v1.22.10
$ node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
C:\xampp\htdocs\mplus\node_modules\webpack-cli\bin\cli.js:93
                                throw err;
                                ^

Error: Missing binding C:\xampp\htdocs\node_modules\node-sass\vendor\win32-x64-72\binding.node
Node Sass could not find a binding for your current environment: Windows 64-bit with Node.js 12.x

Found bindings for the following environments:
  - Windows 64-bit with Node.js 10.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass` to download the binding for your current environment.
    at module.exports (C:\xampp\htdocs\node_modules\node-sass\lib\binding.js:15:13)
    at Object.<anonymous> (C:\xampp\htdocs\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (C:\xampp\htdocs\mplus\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (C:\xampp\htdocs\mplus\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at implementation (C:\xampp\htdocs\mplus\node_modules\laravel-mix\src\components\Sass.js:54:27)
    at C:\xampp\htdocs\mplus\node_modules\laravel-mix\src\components\Preprocessor.js:130:61
    at global.tap (C:\xampp\htdocs\mplus\node_modules\laravel-mix\src\helpers.js:10:5)
    at Sass.loaderOptions (C:\xampp\htdocs\mplus\node_modules\laravel-mix\src\components\Preprocessor.js:128:9)
    at C:\xampp\htdocs\mplus\node_modules\laravel-mix\src\components\Preprocessor.js:87:39
    at global.tap (C:\xampp\htdocs\mplus\node_modules\laravel-mix\src\helpers.js:10:5)
    at C:\xampp\htdocs\mplus\node_modules\laravel-mix\src\components\Preprocessor.js:27:13
    at Array.forEach (<anonymous>)
    at Sass.webpackRules (C:\xampp\htdocs\mplus\node_modules\laravel-mix\src\components\Preprocessor.js:22:22)
    at ComponentFactory.applyRules (C:\xampp\htdocs\mplus\node_modules\laravel-mix\src\components\ComponentFactory.js:155:23)
    at C:\xampp\htdocs\mplus\node_modules\laravel-mix\src\components\ComponentFactory.js:66:48
    at C:\xampp\htdocs\mplus\node_modules\laravel-mix\src\Dispatcher.js:34:47
    at Array.forEach (<anonymous>)
    at Dispatcher.fire (C:\xampp\htdocs\mplus\node_modules\laravel-mix\src\Dispatcher.js:34:28)
    at Mix.dispatch (C:\xampp\htdocs\mplus\node_modules\laravel-mix\src\Mix.js:118:25)
    at WebpackConfig.buildRules (C:\xampp\htdocs\mplus\node_modules\laravel-mix\src\builder\WebpackConfig.js:90:13)
    at WebpackConfig.build (C:\xampp\htdocs\mplus\node_modules\laravel-mix\src\builder\WebpackConfig.js:23:14)
    at Object.<anonymous> (C:\xampp\htdocs\mplus\node_modules\laravel-mix\setup\webpack.config.js:29:38)
    at Module._compile (C:\xampp\htdocs\mplus\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (C:\xampp\htdocs\mplus\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at WEBPACK_OPTIONS (C:\xampp\htdocs\mplus\node_modules\webpack-cli\bin\utils\convert-argv.js:114:13)
    at requireConfig (C:\xampp\htdocs\mplus\node_modules\webpack-cli\bin\utils\convert-argv.js:116:6)
    at C:\xampp\htdocs\mplus\node_modules\webpack-cli\bin\utils\convert-argv.js:123:17
    at Array.forEach (<anonymous>)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by Bottelet** [comment]
Can you try and delete your node_modules folder and do the following?:
```
npm install 
npm run dev
```

Not sure how well the setup works on windows, haven't really tried.

**Comment by lYesterdaYl** [comment]
> Can you try and delete your node_modules folder and do the following?:
> 
> ```
> npm install 
> npm run dev
> ```
> 
> Not sure how well the setup works on windows, haven't really tried.

I just did that. I deleted both vendor and node_modules folders. And run composer install and npm install. But npm run dev always shows the same error above.

**Comment by lYesterdaYl** [comment]
made it work on my server. I guess it is just node.js version problem.
