### ISSUE TITLE
npm install 

### ISSUE THREAD

**Issue by siamsayeed1** [Bottelet/DaybydayCRM#330]
10% building 2/4 modules 2 active ...oader\dist\cjs.js??ref--6-5!C:\xampp\htdocs\crm2\resources\assets\sass\vendor.scssError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (C:\xampp\htdocs\crm2\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\xampp\htdocs\crm2\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\xampp\htdocs\crm2\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\xampp\htdocs\crm2\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\xampp\htdocs\crm2\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\LoaderRunner.js:186:6
    at runSyncOrAsync (C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\LoaderRunner.js:178:3
    at loadLoader (C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\loadLoader.js:47:3)
    at iteratePitchingLoaders (C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\LoaderRunner.js:188:6
    at runSyncOrAsync (C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\LoaderRunner.js:124:12)
    at C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\LoaderRunner.js:178:3
    at loadLoader (C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\loadLoader.js:47:3)
    at iteratePitchingLoaders (C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\LoaderRunner.js:365:2)
    at NormalModule.doBuild (C:\xampp\htdocs\crm2\node_modules\webpack\lib\NormalModule.js:295:3)
    at NormalModule.build (C:\xampp\htdocs\crm2\node_modules\webpack\lib\NormalModule.js:446:15)
    at Compilation.buildModule (C:\xampp\htdocs\crm2\node_modules\webpack\lib\Compilation.js:739:10)
    at C:\xampp\htdocs\crm2\node_modules\webpack\lib\Compilation.js:981:14
    at C:\xampp\htdocs\crm2\node_modules\webpack\lib\NormalModuleFactory.js:409:6
    at C:\xampp\htdocs\crm2\node_modules\webpack\lib\NormalModuleFactory.js:155:13
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (C:\xampp\htdocs\crm2\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at C:\xampp\htdocs\crm2\node_modules\webpack\lib\NormalModuleFactory.js:138:29
    at C:\xampp\htdocs\crm2\node_modules\webpack\lib\NormalModuleFactory.js:346:9
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
10% building 2/5 modules 3 active ...s-loader\dist\cjs.js??ref--5-5!C:\xampp\htdocs\crm2\resources\assets\sass\app.scssError: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (C:\xampp\htdocs\crm2\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\xampp\htdocs\crm2\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\xampp\htdocs\crm2\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\xampp\htdocs\crm2\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\xampp\htdocs\crm2\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\LoaderRunner.js:236:3
    at runSyncOrAsync (C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at iterateNormalLoaders (C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\LoaderRunner.js:186:6
    at runSyncOrAsync (C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\LoaderRunner.js:130:11)
    at C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\LoaderRunner.js:178:3
    at loadLoader (C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\loadLoader.js:47:3)
    at iteratePitchingLoaders (C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\LoaderRunner.js:188:6
    at runSyncOrAsync (C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\LoaderRunner.js:124:12)
    at C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\LoaderRunner.js:178:3
    at loadLoader (C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\loadLoader.js:47:3)
    at iteratePitchingLoaders (C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\LoaderRunner.js:365:2)
    at NormalModule.doBuild (C:\xampp\htdocs\crm2\node_modules\webpack\lib\NormalModule.js:295:3)
    at NormalModule.build (C:\xampp\htdocs\crm2\node_modules\webpack\lib\NormalModule.js:446:15)
    at Compilation.buildModule (C:\xampp\htdocs\crm2\node_modules\webpack\lib\Compilation.js:739:10)
    at C:\xampp\htdocs\crm2\node_modules\webpack\lib\Compilation.js:981:14
    at C:\xampp\htdocs\crm2\node_modules\webpack\lib\NormalModuleFactory.js:409:6
    at C:\xampp\htdocs\crm2\node_modules\webpack\lib\NormalModuleFactory.js:155:13
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (C:\xampp\htdocs\crm2\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at C:\xampp\htdocs\crm2\node_modules\webpack\lib\NormalModuleFactory.js:138:29
    at C:\xampp\htdocs\crm2\node_modules\webpack\lib\NormalModuleFactory.js:346:9
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
node:internal/crypto/hash:79
  this[kHandle] = new _Hash(algorithm, xofLen, algorithmId, getHashCache());
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:79:19)
    at Object.createHash (node:crypto:139:10)
    at module.exports (C:\xampp\htdocs\crm2\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\xampp\htdocs\crm2\node_modules\webpack\lib\NormalModule.js:417:16)
    at C:\xampp\htdocs\crm2\node_modules\webpack\lib\NormalModule.js:452:10
    at C:\xampp\htdocs\crm2\node_modules\webpack\lib\NormalModule.js:323:13
    at C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\xampp\htdocs\crm2\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\xampp\htdocs\crm2\node_modules\babel-loader\lib\index.js:55:103 {
  opensslErrorStack: [
    'error:03000086:digital envelope routines::initialization error',
    'error:0308010C:digital envelope routines::unsupported'
  ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.17.0

C:\xampp\htdocs\crm2>npm audit fix --force
npm warn using --force Recommended protections disabled.
npm warn audit fix debug@4.1.1 node_modules/fsevents/node_modules/debug
npm warn audit fix debug@4.1.1 is a bundled dependency of
npm warn audit fix debug@4.1.1 fsevents@1.2.9 at node_modules/fsevents
npm warn audit fix debug@4.1.1 It cannot be fixed automatically.
npm warn audit fix debug@4.1.1 Check for updates to the fsevents package.
npm warn audit fix semver@5.7.0 node_modules/fsevents/node_modules/semver
npm warn audit fix semver@5.7.0 is a bundled dependency of
npm warn audit fix semver@5.7.0 fsevents@1.2.9 at node_modules/fsevents
npm warn audit fix semver@5.7.0 It cannot be fixed automatically.
npm warn audit fix semver@5.7.0 Check for updates to the fsevents package.
npm warn audit fix minimatch@3.0.4 node_modules/fsevents/node_modules/minimatch
npm warn audit fix minimatch@3.0.4 is a bundled dependency of
npm warn audit fix minimatch@3.0.4 fsevents@1.2.9 at node_modules/fsevents
npm warn audit fix minimatch@3.0.4 It cannot be fixed automatically.
npm warn audit fix minimatch@3.0.4 Check for updates to the fsevents package.
npm warn audit fix minimist@1.2.0 node_modules/fsevents/node_modules/rc/node_modules/minimist
npm warn audit fix minimist@1.2.0 is a bundled dependency of
npm warn audit fix minimist@1.2.0 fsevents@1.2.9 at node_modules/fsevents
npm warn audit fix minimist@1.2.0 It cannot be fixed automatically.
npm warn audit fix minimist@1.2.0 Check for updates to the fsevents package.
npm warn audit fix minimist@0.0.8 node_modules/fsevents/node_modules/minimist
npm warn audit fix minimist@0.0.8 is a bundled dependency of
npm warn audit fix minimist@0.0.8 fsevents@1.2.9 at node_modules/fsevents
npm warn audit fix minimist@0.0.8 It cannot be fixed automatically.
npm warn audit fix minimist@0.0.8 Check for updates to the fsevents package.
npm warn audit fix tar@4.4.8 node_modules/fsevents/node_modules/tar
npm warn audit fix tar@4.4.8 is a bundled dependency of
npm warn audit fix tar@4.4.8 fsevents@1.2.9 at node_modules/fsevents
npm warn audit fix tar@4.4.8 It cannot be fixed automatically.
npm warn audit fix tar@4.4.8 Check for updates to the fsevents package.
npm warn audit fix mkdirp@0.5.1 node_modules/fsevents/node_modules/mkdirp
npm warn audit fix mkdirp@0.5.1 is a bundled dependency of
npm warn audit fix mkdirp@0.5.1 fsevents@1.2.9 at node_modules/fsevents
npm warn audit fix mkdirp@0.5.1 It cannot be fixed automatically.
npm warn audit fix mkdirp@0.5.1 Check for updates to the fsevents package.
npm warn audit Updating vue-template-compiler to 0.1.0, which is a SemVer major change.
npm warn audit Updating laravel-mix to 6.0.49, which is a SemVer major change.
npm warn audit Updating sass-loader to 16.0.1, which is a SemVer major change.
npm warn ERESOLVE overriding peer dependency
npm warn ERESOLVE overriding peer dependency
npm warn While resolving: vis-data@7.1.9
npm warn Found: vis-util@4.3.4
npm warn node_modules/vis-util
npm warn   peer vis-util@"^3.0.0 || ^4.0.0" from vis-timeline@7.4.4
npm warn   node_modules/vis-timeline
npm warn     vis-timeline@"^7.4.4" from the root project
npm warn
npm warn Could not resolve dependency:
npm warn peer vis-util@"^5.0.1" from vis-data@7.1.9
npm warn node_modules/vis-data
npm warn   peer vis-data@"^6.3.0 || ^7.0.0" from vis-timeline@7.4.4
npm warn   node_modules/vis-timeline
npm warn
npm warn Conflicting peer dependency: vis-util@5.0.7
npm warn node_modules/vis-util
npm warn   peer vis-util@"^5.0.1" from vis-data@7.1.9
npm warn   node_modules/vis-data
npm warn     peer vis-data@"^6.3.0 || ^7.0.0" from vis-timeline@7.4.4
npm warn     node_modules/vis-timeline
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.

added 285 packages, removed 455 packages, changed 409 packages, and audited 899 packages in 1m

97 packages are looking for funding
  run `npm fund` for details

# npm audit report

axios  0.8.1 - 0.27.2
Severity: moderate
Axios Cross-Site Request Forgery Vulnerability - https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
fix available via `npm audit fix --force`
Will install axios@1.7.7, which is a breaking change
node_modules/axios

postcss  <8.4.31
Severity: moderate
PostCSS line return parsing error - https://github.com/advisories/GHSA-7fh5-64p2-3v2j
fix available via `npm audit fix --force`
Will install resolve-url-loader@5.0.0, which is a breaking change
node_modules/@vue/component-compiler-utils/node_modules/postcss
node_modules/resolve-url-loader/node_modules/postcss
  @vue/component-compiler-utils  *
  Depends on vulnerable versions of postcss
  node_modules/@vue/component-compiler-utils
    vue-loader  15.0.0-beta.1 - 15.11.1
    Depends on vulnerable versions of @vue/component-compiler-utils
    node_modules/vue-loader
  resolve-url-loader  0.0.1-experiment-postcss || 3.0.0-alpha.1 - 4.0.0
  Depends on vulnerable versions of postcss
  node_modules/resolve-url-loader

semver  <5.7.2
Severity: high
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
fix available via `npm audit fix`
node_modules/semver

6 vulnerabilities (5 moderate, 1 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

C:\xampp\htdocs\crm2>npm run dev

> dev
> node node_modules/cross-env/dist/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

[webpack-cli] Error: Unknown option '--hide-modules'
[webpack-cli] Run 'webpack --help' to see available commands and options

**Comment by Bottelet** [comment]
You probably need to use an older node version than what you are using. or feel free to make a PR to upgrade Laravel / node etc.
